# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f06d30b89d3fc7c0603266e72ecd1ffabd1d2c445d1db31ac385b3a9fec5b1c03b7237330a6eda68971035fb93ee5f95669fc560056f3df5283eff4b2c866f9f

test:
  secret_key_base: e6f1518c57d59115d63d0915f90d21101c6b996c038f33981787db3d0b567eed70f17a5b01da2372740ef78bdf59ece579981dec8559657db9876b2ebdd2fa23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
